// src/pages/app/privacy.vue
<style lang="less" scoped>
article {
  padding: 4rem 0;
}
</style>

<template>
  <s-section>
    <article className="markdown-body">
      <h1 id="-">隐私政策</h1>
      <p>
        <strong>更新日期：2025 年 8 月</strong>
      </p>
      <h2 id="-">引言</h2>
      <p>
        亿信数科（以下简称“我们”或“本公司”）深知个人信息对您的重要性，并会尽全力保护您的个人信息安全可靠。我们致力于维持您对我们的信任，恪守以下原则，保护您的个人信息：<strong>权责一致原则、目的明确原则、选择同意原则、最少够用原则、确保安全原则、主体参与原则、公开透明原则</strong>等。
        <br />
        本隐私政策（以下简称“本政策”）适用于本公司通过网站（<a href="http://www.fdev.work">www.fdev.work</a>）向您提供的产品和服务。请您在使用我们的产品或服务前，仔细阅读并充分理解本政策。
      </p>
      <hr />
      <h2 id="-">一、我们如何收集和使用您的个人信息</h2>
      <h3 id="1-1-">1.1 我们收集的信息类型</h3>
      <p>在您使用我们的服务过程中，我们可能会收集以下信息：</p>
      <p>
        <strong>（1）您主动提供的信息</strong>
      </p>
      <ul>
        <li>联系信息：当您填写表单、订阅资讯或与我们联系时，您可能需要提供姓名、电子邮箱、手机号码、公司名称等信息。</li>
        <li>咨询内容：您向我们提出的问题、建议或反馈内容。</li>
      </ul>
      <p>
        <strong>（2）我们自动收集的信息</strong>
      </p>
      <ul>
        <li>设备信息：设备型号、操作系统版本、设备识别码、屏幕分辨率等。</li>
        <li>日志信息：IP 地址、浏览器类型及版本、访问时间、访问页面记录、停留时长、点击记录等。</li>
        <li>Cookie 和类似技术：我们使用 Cookie 及类似技术收集您的偏好设置、会话信息等。</li>
      </ul>
      <h3 id="1-2-">1.2 我们如何使用收集的信息</h3>
      <p>我们会将收集的信息用于以下用途：</p>
      <ul>
        <li><strong>提供服务</strong>：响应您的咨询请求，向您发送您订阅的资讯内容；</li>
        <li><strong>改善服务</strong>：分析网站使用情况，优化用户体验，改进我们的产品和服务；</li>
        <li><strong>安全保障</strong>：检测、预防和处理欺诈、安全漏洞或其他潜在的技术问题；</li>
        <li><strong>统计分析</strong>：进行匿名化、去标识化的统计分析，了解用户群体特征和使用趋势；</li>
        <li><strong>营销沟通</strong>：在获得您同意的前提下，向您发送产品更新、活动信息等营销内容。</li>
      </ul>
      <hr />
      <h2 id="-cookie-">二、我们如何使用 Cookie 和同类技术</h2>
      <h3 id="2-1-cookie-">2.1 Cookie 的使用</h3>
      <p>Cookie 是一种可以让网站服务器将数据存储于客户端或从客户端读取数据的技术。当您访问我们的网站时，我们可能会在您的设备上存储 Cookie，用于：</p>
      <ul>
        <li>记住您的偏好设置；</li>
        <li>分析网站流量和使用情况；</li>
        <li>提供个性化的用户体验；</li>
        <li>进行广告效果评估。</li>
      </ul>
      <h3 id="2-2-cookie">2.2 如何管理 Cookie</h3>
      <p>大多数浏览器均允许您管理 Cookie 偏好设置。您可以设置浏览器拒绝 Cookie 或在收到 Cookie 时提醒您。但请注意，如果您选择禁用 Cookie，可能会影响网站某些功能的正常使用。</p>
      <hr />
      <h2 id="-">三、我们如何共享、转让、公开披露您的个人信息</h2>
      <h3 id="3-1-">3.1 共享</h3>
      <p>我们不会向第三方共享您的个人信息，但以下情况除外：</p>
      <ul>
        <li>获得您的明确同意；</li>
        <li>服务提供商：我们可能会与提供技术支持、数据分析、营销推广等服务的第三方服务提供商共享您的信息，但我们会要求其遵守保密义务；</li>
        <li>法律要求：根据法律法规、诉讼、政府主管部门的要求进行披露。</li>
      </ul>
      <h3 id="3-2-">3.2 转让</h3>
      <p>我们不会将您的个人信息转让给任何公司、组织和个人，但以下情况除外：</p>
      <ul>
        <li>在获得您的明确同意后；</li>
        <li>在涉及合并、收购或破产清算时，如涉及个人信息转让，我们会要求新的持有您个人信息的公司继续受本政策的约束。</li>
      </ul>
      <h3 id="3-3-">3.3 公开披露</h3>
      <p>我们仅会在以下情况下公开披露您的个人信息：</p>
      <ul>
        <li>获得您的明确同意；</li>
        <li>基于法律法规的要求。</li>
      </ul>
      <hr />
      <h2 id="-">四、我们如何保护您的个人信息</h2>
      <h3 id="4-1-">4.1 安全措施</h3>
      <p>我们采取以下措施保护您的个人信息：</p>
      <ul>
        <li><strong>技术措施</strong>：采用加密技术（如 SSL）、匿名化处理、访问控制等技术手段；</li>
        <li><strong>管理措施</strong>：建立数据安全管理制度，对员工进行数据安全培训，限制数据访问权限；</li>
        <li><strong>物理措施</strong>：对存储数据的服务器进行物理保护。</li>
      </ul>
      <h3 id="4-2-">4.2 安全事件处置</h3>
      <p>若发生个人信息泄露等安全事件，我们将依法启动应急预案，采取相应的补救措施，并通过网站公告、电子邮件等方式告知您。</p>
      <hr />
      <h2 id="-">五、您的权利</h2>
      <p>根据相关法律法规，您对自己的个人信息享有以下权利：</p>
      <ul>
        <li><strong>访问权</strong>：您有权访问您的个人信息；</li>
        <li><strong>更正权</strong>：当您发现我们处理的关于您的个人信息有错误时，您有权要求我们更正；</li>
        <li><strong>删除权</strong>：在法律规定的情形中，您可以向我们提出删除个人信息的请求；</li>
        <li><strong>撤回同意</strong>：您可通过隐私设置等方式撤回授权；</li>
        <li><strong>注销账户</strong>：如服务提供账户注册功能，您可以申请注销账户。</li>
      </ul>
      <hr />
      <h2 id="-">六、我们如何处理未成年人的个人信息</h2>
      <p>
        我们的产品、网站和服务主要面向成年人。未满 18 周岁的未成年人，若无父母或监护人同意，不应创建账户或向我们提供个人信息。
        <br />
        若我们在未获监护人同意的情况下收集了未成年人的个人信息，我们将尽快删除。
      </p>
      <hr />
      <h2 id="-">七、您的个人信息如何在全球范围转移</h2>
      <p>原则上，我们在中华人民共和国境内收集和产生的个人信息，将存储在境内。如需跨境传输，我们将征得您的授权同意，并严格遵守相关法律法规。</p>
      <hr />
      <h2 id="-">八、本政策如何更新</h2>
      <p>我们可能会适时修订本政策的条款，并在网站上公示。对于重大变更，我们将通过显著方式（如网站公告、电子邮件等）通知您。</p>
      <p>
        <strong>重大变更包括但不限于：</strong>
      </p>
      <ul>
        <li>服务模式发生重大变化；</li>
        <li>共享、转让或公开披露个人信息的主要对象发生变化；</li>
        <li>您在个人信息处理中的权利及行使方式发生重大变化；</li>
        <li>我们的联系方式及投诉渠道发生变化。</li>
      </ul>
      <hr />
      <h2 id="-">九、如何联系我们</h2>
      <p>如您对本隐私政策有任何疑问、意见或建议，请通过以下方式联系我们：</p>
      <p>
        <strong>公司名称</strong>：上海亿信数科信息技术有限公司
        <br />
        <strong>注册地址</strong>：上海市崇明区横沙乡红丰路 33 号（上海横泰经济开发区）
        <br />
        <strong>联系邮箱</strong>：<a href="mailto:	support@billionsintelligence.com">support@billionsintelligence.com</a>
        <br />
        <strong>联系电话</strong>：<a href="tel:15754308709">15754308709</a>
      </p>
      <p>一般情况下，我们将在十五个工作日内回复。若您认为我们的处理行为损害了您的合法权益，您可向网信、公安及工商等监管部门投诉或举报。</p>
      <hr />
      <h2 id="-">附录：定义</h2>
      <p>
        <strong>个人信息</strong>：以电子或其他方式记录的能够单独或与其他信息结合识别特定自然人身份或反映其活动情况的各种信息。
        <br />
        <strong>个人敏感信息</strong>：包括身份证件号码、个人生物识别信息、银行账号、财产信息、行踪轨迹、交易信息、14 岁以下（含）儿童信息等。
        <br />
        <strong>设备</strong>：指可用于访问我们服务的装置，例如台式电脑、笔记本电脑、平板电脑或智能手机。
      </p>
    </article>
  </s-section>
</template>

<script>
export default {};
</script>

// components/Privacy.tsx
'use client';

import React from 'react';

const FoundingTeam: React.FC = () => {
  return (
    <article className="markdown-body">
      <h1 id="-">隐私政策</h1>
      <p>
        <strong>更新日期：2025 年 8 月</strong>
      </p>
      <h2 id="-">引言</h2>
      <p>
        亿信数科（以下简称“我们”或“本公司”）深知个人信息对您的重要性，并会尽全力保护您的个人信息安全可靠。我们致力于维持您对我们的信任，恪守以下原则，保护您的个人信息：<strong>权责一致原则、目的明确原则、选择同意原则、最少够用原则、确保安全原则、主体参与原则、公开透明原则</strong>等。
        <br />
        本隐私政策（以下简称“本政策”）适用于本公司通过网站（<a href="http://www.billionsintelligence.com">www.billionsintelligence.com</a>）向您提供的产品和服务。请您在使用我们的产品或服务前，仔细阅读并充分理解本政策。
      </p>
      <hr />
      <h2 id="-">一、我们如何收集和使用您的个人信息</h2>
      <h3 id="1-1-">1.1 我们收集的信息类型</h3>
      <p>在您使用我们的服务过程中，我们可能会收集以下信息：</p>
      <p>
        <strong>（1）您主动提供的信息</strong>
      </p>
      <ul>
        <li>联系信息：当您填写表单、订阅资讯或与我们联系时，您可能需要提供姓名、电子邮箱、手机号码、公司名称等信息。</li>
        <li>咨询内容：您向我们提出的问题、建议或反馈内容。</li>
      </ul>
      <p>
        <strong>（2）我们自动收集的信息</strong>
      </p>
      <ul>
        <li>设备信息：设备型号、操作系统版本、设备识别码、屏幕分辨率等。</li>
        <li>日志信息：IP 地址、浏览器类型及版本、访问时间、访问页面记录、停留时长、点击记录等。</li>
        <li>Cookie 和类似技术：我们使用 Cookie 及类似技术收集您的偏好设置、会话信息等。</li>
      </ul>
      <h3 id="1-2-">1.2 我们如何使用收集的信息</h3>
      <p>我们会将收集的信息用于以下用途：</p>
      <ul>
        <li>
          <strong>提供服务</strong>：响应您的咨询请求，向您发送您订阅的资讯内容；
        </li>
        <li>
          <strong>改善服务</strong>：分析网站使用情况，优化用户体验，改进我们的产品和服务；
        </li>
        <li>
          <strong>安全保障</strong>：检测、预防和处理欺诈、安全漏洞或其他潜在的技术问题；
        </li>
        <li>
          <strong>统计分析</strong>：进行匿名化、去标识化的统计分析，了解用户群体特征和使用趋势；
        </li>
        <li>
          <strong>营销沟通</strong>：在获得您同意的前提下，向您发送产品更新、活动信息等营销内容。
        </li>
      </ul>
      <hr />
      <h2 id="-cookie-">二、我们如何使用 Cookie 和同类技术</h2>
      <h3 id="2-1-cookie-">2.1 Cookie 的使用</h3>
      <p>Cookie 是一种可以让网站服务器将数据存储于客户端或从客户端读取数据的技术。当您访问我们的网站时，我们可能会在您的设备上存储 Cookie，用于：</p>
      <ul>
        <li>记住您的偏好设置；</li>
        <li>分析网站流量和使用情况；</li>
        <li>提供个性化的用户体验；</li>
        <li>进行广告效果评估。</li>
      </ul>
      <h3 id="2-2-cookie">2.2 如何管理 Cookie</h3>
      <p>大多数浏览器均允许您管理 Cookie 偏好设置。您可以设置浏览器拒绝 Cookie 或在收到 Cookie 时提醒您。但请注意，如果您选择禁用 Cookie，可能会影响网站某些功能的正常使用。</p>
      <hr />
      <h2 id="-">三、我们如何共享、转让、公开披露您的个人信息</h2>
      <h3 id="3-1-">3.1 共享</h3>
      <p>我们不会向第三方共享您的个人信息，但以下情况除外：</p>
      <ul>
        <li>获得您的明确同意；</li>
        <li>服务提供商：我们可能会与提供技术支持、数据分析、营销推广等服务的第三方服务提供商共享您的信息，但我们会要求其遵守保密义务；</li>
        <li>法律要求：根据法律法规、诉讼、政府主管部门的要求进行披露。</li>
      </ul>
      <h3 id="3-2-">3.2 转让</h3>
      <p>我们不会将您的个人信息转让给任何公司、组织和个人，但以下情况除外：</p>
      <ul>
        <li>在获得您的明确同意后；</li>
        <li>在涉及合并、收购或破产清算时，如涉及个人信息转让，我们会要求新的持有您个人信息的公司继续受本政策的约束。</li>
      </ul>
      <h3 id="3-3-">3.3 公开披露</h3>
      <p>我们仅会在以下情况下公开披露您的个人信息：</p>
      <ul>
        <li>获得您的明确同意；</li>
        <li>基于法律法规的要求。</li>
      </ul>
      <hr />
      <h2 id="-">四、我们如何保护您的个人信息</h2>
      <h3 id="4-1-">4.1 安全措施</h3>
      <p>我们采取以下措施保护您的个人信息：</p>
      <ul>
        <li>
          <strong>技术措施</strong>：采用加密技术（如 SSL）、匿名化处理、访问控制等技术手段；
        </li>
        <li>
          <strong>管理措施</strong>：建立数据安全管理制度，对员工进行数据安全培训，限制数据访问权限；
        </li>
        <li>
          <strong>物理措施</strong>：对存储数据的服务器进行物理保护。
        </li>
      </ul>
      <h3 id="4-2-">4.2 安全事件处置</h3>
      <p>若发生个人信息泄露等安全事件，我们将依法启动应急预案，采取相应的补救措施，并通过网站公告、电子邮件等方式告知您。</p>
      <hr />
      <h2 id="-">五、您的权利</h2>
      <p>根据相关法律法规，您对自己的个人信息享有以下权利：</p>
      <ul>
        <li>
          <strong>访问权</strong>：您有权访问您的个人信息；
        </li>
        <li>
          <strong>更正权</strong>：当您发现我们处理的关于您的个人信息有错误时，您有权要求我们更正；
        </li>
        <li>
          <strong>删除权</strong>：在法律规定的情形中，您可以向我们提出删除个人信息的请求；
        </li>
        <li>
          <strong>撤回同意</strong>：您可通过隐私设置等方式撤回授权；
        </li>
        <li>
          <strong>注销账户</strong>：如服务提供账户注册功能，您可以申请注销账户。
        </li>
      </ul>
      <hr />
      <h2 id="-">六、我们如何处理未成年人的个人信息</h2>
      <p>
        我们的产品、网站和服务主要面向成年人。未满 18 周岁的未成年人，若无父母或监护人同意，不应创建账户或向我们提供个人信息。
        <br />
        若我们在未获监护人同意的情况下收集了未成年人的个人信息，我们将尽快删除。
      </p>
      <hr />
      <h2 id="-">七、您的个人信息如何在全球范围转移</h2>
      <p>原则上，我们在中华人民共和国境内收集和产生的个人信息，将存储在境内。如需跨境传输，我们将征得您的授权同意，并严格遵守相关法律法规。</p>
      <hr />
      <h2 id="-">八、本政策如何更新</h2>
      <p>我们可能会适时修订本政策的条款，并在网站上公示。对于重大变更，我们将通过显著方式（如网站公告、电子邮件等）通知您。</p>
      <p>
        <strong>重大变更包括但不限于：</strong>
      </p>
      <ul>
        <li>服务模式发生重大变化；</li>
        <li>共享、转让或公开披露个人信息的主要对象发生变化；</li>
        <li>您在个人信息处理中的权利及行使方式发生重大变化；</li>
        <li>我们的联系方式及投诉渠道发生变化。</li>
      </ul>
      <hr />
      <h2 id="-">九、如何联系我们</h2>
      <p>如您对本隐私政策有任何疑问、意见或建议，请通过以下方式联系我们：</p>
      <p>
        <strong>公司名称</strong>：上海亿信数科信息技术有限公司
        <br />
        <strong>注册地址</strong>：上海市崇明区横沙乡红丰路 33 号（上海横泰经济开发区）
        <br />
        <strong>联系邮箱</strong>：<a href="mailto:	support@billionsintelligence.com">support@billionsintelligence.com</a>
        <br />
        <strong>联系电话</strong>：<a href="tel:15754308709">15754308709</a>
      </p>
      <p>一般情况下，我们将在十五个工作日内回复。若您认为我们的处理行为损害了您的合法权益，您可向网信、公安及工商等监管部门投诉或举报。</p>
      <hr />
      <h2 id="-">附录：定义</h2>
      <p>
        <strong>个人信息</strong>：以电子或其他方式记录的能够单独或与其他信息结合识别特定自然人身份或反映其活动情况的各种信息。
        <br />
        <strong>个人敏感信息</strong>：包括身份证件号码、个人生物识别信息、银行账号、财产信息、行踪轨迹、交易信息、14 岁以下（含）儿童信息等。
        <br />
        <strong>设备</strong>：指可用于访问我们服务的装置，例如台式电脑、笔记本电脑、平板电脑或智能手机。
      </p>
    </article>
  );
};

export default FoundingTeam;
